Dune.buildingsList = [
	[
		[ 'silo'   ,   0,   0 ],
		[ 'plate'  ,   2,   0 ],
		[ 'plate'  ,   3,   0 ],
		[ 'plate'  ,   4,   0 ],
		[ 'plate'  ,   5,   0 ],
		[ 'plate'  ,   6,   0 ],
		[ 'plate'  ,   7,   0 ],
		[ 'plate'  ,   8,   0 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   0,   2 ],
		[ 'plate'  ,   1,   2 ],
		[ 'plate'  ,   2,   2 ],
		[ 'factory',   3,   1 ],
		[ 'plate'  ,   2,   3 ],
		[ 'radar'  ,   0,   3 ],
		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   7,   3 ],
		[ 'plate'  ,   8,   3 ],
		[ 'power'  ,   2,   4 ],
		[ 'power'  ,   4,   4 ],
		[ 'power'  ,   6,   4 ],
		[ 'harvest',   6,   1 ],
		[ 'silo'   ,   0,   5 ],
		[ 'silo'   ,   0,   7 ],
		[ 'plate'  ,   8,   4 ],
		[ 'plate'  ,   8,   5 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   7,   6 ],
		[ 'plate'  ,   8,   6 ],
		[ 'plate'  ,   2,   7 ],
		[ 'plate'  ,   2,   8 ],
		[ 'plate'  ,   6,   7 ],
		[ 'harvest',   3,   7 ]
	],
	[
		[ 'radar'  ,   0,   0 ],
		[ 'plate'  ,   2,   0 ],
		[ 'plate'  ,   3,   0 ],
		[ 'plate'  ,   4,   0 ],
		[ 'plate'  ,   5,   0 ],
		[ 'plate'  ,   6,   0 ],
		[ 'plate'  ,   7,   0 ],
		[ 'plate'  ,   8,   0 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   0,   2 ],
		[ 'plate'  ,   1,   2 ],
		[ 'plate'  ,   2,   2 ],
		[ 'plate'  ,   2,   3 ],
		[ 'plate'  ,   2,   4 ],
		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   7,   3 ],
		[ 'plate'  ,   8,   3 ],
		[ 'harvest',   6,   4 ],
		[ 'harvest',   3,   4 ],
		[ 'factory',   3,   7 ],
		[ 'silo'  ,   3,   1 ],
		[ 'silo'  ,   5,   1 ],
		[ 'silo'  ,   7,   1 ],
		[ 'power'   ,   0,   5 ],
		[ 'power'   ,   0,   3 ],
		[ 'power'   ,   0,   7 ],
		[ 'plate'  ,   2,   5 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   7,   6 ],
		[ 'plate'  ,   8,   6 ],
		[ 'plate'  ,   2,   7 ],
		[ 'plate'  ,   2,   8 ],
		[ 'plate'  ,   6,   7 ]
	]
];