Dune.buildingsList = [
	[
		[ 'silo'   ,   0,   0 ],
		[ 'plate'  ,   2,   0 ],
		[ 'plate'  ,   3,   0 ],
		[ 'plate'  ,   4,   0 ],
		[ 'plate'  ,   5,   0 ],
		[ 'plate'  ,   6,   0 ],
		[ 'plate'  ,   7,   0 ],
		[ 'plate'  ,   8,   0 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   0,   2 ],
		[ 'plate'  ,   1,   2 ],
		[ 'plate'  ,   2,   2 ],
		[ 'factory',   3,   1 ],
		[ 'plate'  ,   2,   3 ],
		[ 'radar'  ,   0,   3 ],
		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   7,   3 ],
		[ 'plate'  ,   8,   3 ],
		[ 'power'  ,   2,   4 ],
		[ 'power'  ,   4,   4 ],
		[ 'power'  ,   6,   4 ],
		[ 'harvest',   6,   1 ],
		[ 'silo'   ,   0,   5 ],
		[ 'silo'   ,   0,   7 ],
		[ 'plate'  ,   8,   4 ],
		[ 'plate'  ,   8,   5 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   7,   6 ],
		[ 'plate'  ,   8,   6 ],
		[ 'plate'  ,   2,   7 ],
		[ 'plate'  ,   2,   8 ],
		[ 'plate'  ,   6,   7 ],
		[ 'harvest',   3,   7 ]
	], [
		[ 'radar'  ,   0,   0 ],
		[ 'plate'  ,   2,   0 ],
		[ 'plate'  ,   3,   0 ],
		[ 'plate'  ,   4,   0 ],
		[ 'plate'  ,   5,   0 ],
		[ 'plate'  ,   6,   0 ],
		[ 'plate'  ,   7,   0 ],
		[ 'plate'  ,   8,   0 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   0,   2 ],
		[ 'plate'  ,   1,   2 ],
		[ 'plate'  ,   2,   2 ],
		[ 'plate'  ,   2,   3 ],
		[ 'plate'  ,   2,   4 ],
		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   7,   3 ],
		[ 'plate'  ,   8,   3 ],
		[ 'harvest',   6,   4 ],
		[ 'harvest',   3,   4 ],
		[ 'factory',   3,   7 ],
		[ 'silo'  ,   3,   1 ],
		[ 'silo'  ,   5,   1 ],
		[ 'silo'  ,   7,   1 ],
		[ 'power'   ,   0,   5 ],
		[ 'power'   ,   0,   3 ],
		[ 'power'   ,   0,   7 ],
		[ 'plate'  ,   2,   5 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   7,   6 ],
		[ 'plate'  ,   8,   6 ],
		[ 'plate'  ,   2,   7 ],
		[ 'plate'  ,   2,   8 ],
		[ 'plate'  ,   6,   7 ]
	], [
		[ 'power'  ,   0,   0 ],
		[ 'plate'  ,   2,   0 ],
		[ 'plate'  ,   3,   0 ],
		[ 'plate'  ,   4,   0 ],
		[ 'plate'  ,   5,   0 ],
		[ 'plate'  ,   6,   0 ],
		[ 'plate'  ,   7,   0 ],
		[ 'plate'  ,   8,   0 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   0,   2 ],
		[ 'plate'  ,   1,   2 ],
		[ 'plate'  ,   2,   2 ],
		[ 'plate'  ,   2,   3 ],
		[ 'plate'  ,   2,   4 ],
		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   7,   3 ],
		[ 'plate'  ,   7,   6 ],
		[ 'harvest',   6,   1 ],
		[ 'harvest',   3,   1 ],
		[ 'harvest',   3,   4 ],
		[ 'silo'   ,   3,   7 ],
		[ 'silo'   ,   5,   7 ],
		[ 'silo'   ,   7,   7 ],
		[ 'silo'   ,   7,   4 ],
		[ 'silo'   ,   0,   5 ],
		[ 'silo'   ,   0,   3 ],
		[ 'silo'   ,   0,   7 ],
		[ 'plate'  ,   2,   5 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   2,   7 ],
		[ 'plate'  ,   2,   8 ],
		[ 'plate'  ,   6,   4 ],
		[ 'plate'  ,   6,   5 ]
	], [
		[ 'plate'  ,   3,   2 ],
		[ 'plate'  ,   4,   2 ],
		[ 'plate'  ,   5,   2 ],
		[ 'plate'  ,   6,   2 ],
		[ 'plate'  ,   7,   2 ],
		[ 'plate'  ,   6,   3 ],
		[ 'plate'  ,   6,   4 ],
		[ 'plate'  ,   6,   5 ],
		[ 'plate'  ,   6,   6 ],
		[ 'plate'  ,   6,   7 ],
		[ 'plate'  ,   1,   6 ],
		[ 'plate'  ,   2,   6 ],
		[ 'plate'  ,   3,   6 ],
		[ 'plate'  ,   4,   6 ],
		[ 'plate'  ,   5,   6 ],
		[ 'plate'  ,   2,   1 ],
		[ 'plate'  ,   2,   2 ],
		[ 'plate'  ,   2,   3 ],
		[ 'plate'  ,   2,   4 ],
		[ 'plate'  ,   2,   5 ], // 24

		[ 'power'  ,   0,   0 ],
		[ 'power'  ,   0,   2 ],
		[ 'power'  ,   0,   4 ],

		[ 'power'  ,   3,   0 ],
		[ 'power'  ,   5,   0 ],
		[ 'power'  ,   7,   0 ],

		[ 'power'  ,   0,   7 ],
		[ 'power'  ,   2,   7 ],
		[ 'power'  ,   4,   7 ],

		[ 'power'  ,   7,   3 ],
		[ 'power'  ,   7,   5 ],
		[ 'power'  ,   7,   7 ],

		[ 'plate'  ,   3,   3 ],
		[ 'plate'  ,   3,   5 ],
		[ 'plate'  ,   5,   3 ],
		[ 'plate'  ,   5,   5 ],
		[ 'plate'  ,   3,   4 ],
		[ 'plate'  ,   4,   3 ],
		[ 'plate'  ,   4,   5 ],
		[ 'plate'  ,   5,   4 ]
	]
];